Fix bug, Error: listen EADDRINUSE :::3000
At one point the following error was thrown in the console:
Error: listen EADDRINUSE :::3000

I tried a few different steps including reinstalling nodemon.

But in the end I needed to quit vscode,
run this comman in terminal:
lsof -n -i:3000
and then this command:
kill -9 {process_number}